#!/bin/sh

BASE_PATH=$(python3 -c 'import pdaltagent; print(pdaltagent.__path__[0])')
LIB_PATH="${BASE_PATH}/plugin-lib"

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 PIP_PACKAGE_NAME" >&2
  exit 1
fi

pip install --target ${LIB_PATH} $1
